"""RFC 5545 iCalendar export support for Planix exam schedules.

The exporter intentionally serializes only the exams that appear on the active
schedule. Internal scheduling metadata such as excluded days, holiday blocks,
study-gap constraints, ranking metrics, and generation/debug lines are not part
of the calendar payload.
"""
from __future__ import annotations

import hashlib
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import Iterable, List

from src.MVP.models.schedule import Schedule, ScheduledExam

CRLF = "\r\n"


class CalendarIcsExporter:
    """Build and write standards-compliant all-day iCalendar exam events."""

    PRODUCT_ID = "-//Planix//Exam Schedule Export//EN"
    DEFAULT_CALENDAR_NAME = "Planix Exam Schedule"

    def export_schedule(
        self,
        schedule: Schedule,
        destination_path: str,
        calendar_name: str = DEFAULT_CALENDAR_NAME,
    ) -> str:
        """Write *schedule* as an .ics file and return the destination path."""
        self._validate_schedule(schedule)
        destination = self._validate_destination(destination_path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        with open(destination, "w", encoding="utf-8", newline="") as f:
            f.write(self.build_calendar(schedule, calendar_name=calendar_name))
        return str(destination)

    def build_calendar(
        self,
        schedule: Schedule,
        calendar_name: str = DEFAULT_CALENDAR_NAME,
        generated_at: datetime | None = None,
    ) -> str:
        """Return the RFC 5545 text for the active exam schedule."""
        self._validate_schedule(schedule)
        generated_at = self._normalize_timestamp(generated_at)
        dtstamp = generated_at.strftime("%Y%m%dT%H%M%SZ")

        lines: List[str] = [
            "BEGIN:VCALENDAR",
            "VERSION:2.0",
            f"PRODID:{self.PRODUCT_ID}",
            "CALSCALE:GREGORIAN",
            "METHOD:PUBLISH",
            f"X-WR-CALNAME:{self._escape_text(calendar_name)}",
        ]

        for event_index, exam in enumerate(self._active_exam_events(schedule), start=1):
            lines.extend(self._event_lines(exam, event_index, dtstamp))

        lines.append("END:VCALENDAR")
        return CRLF.join(self._fold_line(line) for line in lines) + CRLF

    def _event_lines(self, exam: ScheduledExam, event_index: int, dtstamp: str) -> List[str]:
        course = exam.course
        exam_date = exam.exam_date
        end_date = exam_date + timedelta(days=1)
        course_id = str(getattr(course, "course_id", "")).strip()
        course_name = str(getattr(course, "course_name", "")).strip()
        instructor = str(getattr(course, "instructor", "")).strip()
        evaluation_method = str(getattr(course, "evaluation_method", "")).strip()

        summary_core = " - ".join(part for part in (course_id, course_name) if part)
        summary = f"Exam: {summary_core}" if summary_core else "Planix Exam"
        uid = self._build_uid(exam, event_index)
        description_parts = [
            f"Course ID: {course_id}" if course_id else "",
            f"Course name: {course_name}" if course_name else "",
            f"Instructor: {instructor}" if instructor else "",
            f"Evaluation method: {evaluation_method}" if evaluation_method else "",
            "Generated by Planix",
        ]
        description = "\n".join(part for part in description_parts if part)

        return [
            "BEGIN:VEVENT",
            f"UID:{uid}",
            f"DTSTAMP:{dtstamp}",
            f"DTSTART;VALUE=DATE:{exam_date.strftime('%Y%m%d')}",
            f"DTEND;VALUE=DATE:{end_date.strftime('%Y%m%d')}",
            f"SUMMARY:{self._escape_text(summary)}",
            f"DESCRIPTION:{self._escape_text(description)}",
            "TRANSP:OPAQUE",
            "END:VEVENT",
        ]

    def _active_exam_events(self, schedule: Schedule) -> List[ScheduledExam]:
        exams = [exam for exam in (schedule.exams or []) if self._is_exportable_exam(exam)]
        return sorted(
            exams,
            key=lambda exam: (
                exam.exam_date,
                str(getattr(exam.course, "course_id", "")),
                str(getattr(exam.course, "course_name", "")),
            ),
        )

    @staticmethod
    def _is_exportable_exam(exam) -> bool:
        return (
            isinstance(exam, ScheduledExam)
            and isinstance(getattr(exam, "exam_date", None), date)
            and getattr(exam, "course", None) is not None
        )

    @staticmethod
    def _build_uid(exam: ScheduledExam, event_index: int) -> str:
        course = exam.course
        raw = "|".join(
            [
                str(getattr(course, "course_id", "")),
                str(getattr(course, "course_name", "")),
                exam.exam_date.isoformat(),
                str(event_index),
            ]
        )
        digest = hashlib.sha1(raw.encode("utf-8")).hexdigest()[:16]
        return f"planix-{exam.exam_date.strftime('%Y%m%d')}-{digest}@planix.local"

    @staticmethod
    def _escape_text(value: str) -> str:
        """Escape TEXT values according to RFC 5545 section 3.3.11."""
        return (
            str(value)
            .replace("\\", "\\\\")
            .replace(";", r"\;")
            .replace(",", r"\,")
            .replace("\r\n", r"\n")
            .replace("\n", r"\n")
            .replace("\r", r"\n")
        )

    @staticmethod
    def _fold_line(line: str) -> str:
        """Fold content lines to 75 octets without splitting UTF-8 characters."""
        encoded = line.encode("utf-8")
        if len(encoded) <= 75:
            return line

        folded_parts: List[str] = []
        current = ""
        current_len = 0
        limit = 75

        for char in line:
            char_len = len(char.encode("utf-8"))
            if current and current_len + char_len > limit:
                folded_parts.append(current)
                current = " " + char
                current_len = 1 + char_len
                limit = 75
            else:
                current += char
                current_len += char_len
        if current:
            folded_parts.append(current)
        return CRLF.join(folded_parts)

    @staticmethod
    def _normalize_timestamp(value: datetime | None) -> datetime:
        if value is None:
            return datetime.now(timezone.utc)
        if value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)
        return value.astimezone(timezone.utc)

    @staticmethod
    def _validate_schedule(schedule: Schedule) -> None:
        if not isinstance(schedule, Schedule):
            raise TypeError("schedule must be a Schedule instance.")

    @staticmethod
    def _validate_destination(destination_path: str) -> Path:
        if not isinstance(destination_path, str):
            raise TypeError("destination_path must be a string.")
        normalized = destination_path.strip()
        if not normalized:
            raise ValueError("destination_path cannot be empty.")
        return Path(normalized)
