# src/MVP/views/theme.py

# --- Colors: (Light Mode, Dark Mode) ---
# App background: soft sky-blue by day, deep charcoal-blue at night
BG_MAIN = ("#e3f2f7", "#122330")

# Card background - at night we added a subtle bluish tint instead of plain gray
BG_CARD = ("#ffffff", "#1e2b3c")
BG_CARD_HOVER = ("#f8f9fa", "#263648")

BORDER_DEFAULT = ("#dee2e6", "#2c3e50")

# Unified accent color! Deep blue by day (for contrast), and glowing sky-blue at night
BORDER_ACTIVE = ("#0077b6", "#38b6ff")
TEXT_ACCENT = ("#0077b6", "#38b6ff")
ACCENT_HOVER = ("#005f8a", "#2f7ab0")

TEXT_MAIN = ("#212529", "#ffffff")
TEXT_MUTED = ("#6c757d", "#9ba4b5")
TEXT_ON_ACCENT = ("#ffffff", "#ffffff")
TOOLTIP_BG = ("#2c3e50", "#1a252f")

SUCCESS = ("#198754", "#2ecc71")
SUCCESS_HOVER = ("#157347", "#27ae60")

DANGER = ("#dc3545", "#ff4d4d")
DANGER_HOVER = ("#c82333", "#ff6b6b")

TRANSPARENT = "transparent"

# --- Border widths ---
BORDER_WIDTH_NONE = 0
BORDER_WIDTH_DEFAULT = 1
BORDER_WIDTH_ACTIVE = 2

# --- Radiuses ---
RADIUS_NONE = 0
RADIUS_SMALL = 6
RADIUS_BUTTON = 8
RADIUS_BAR = 10
RADIUS_CARD = 16
RADIUS_ROUND = 15

# --- Spacings ---
SPACING_NONE = 0
SPACING_XXS = 1
SPACING_XS = 2
SPACING_TINY = 4
SPACING_SMALL = 8
SPACING_COMPACT = 10
SPACING_REGULAR = 16
SPACING_MEDIUM = 20
SPACING_LARGE = 24
SPACING_XL = 30
SPACING_SECTION = 32
SPACING_MODAL = 36
SPACING_SEPARATOR = 40

# --- Fonts ---
FONT_FAMILY = "Rubik"
FONT_ICON = "Segoe UI Emoji"
FONT_BOOTSTRAP_ICONS = "bootstrap-icons"
FONT_WEIGHT_BOLD = "bold"

FONT_SIZE_XS = 11
FONT_SIZE_SMALL = 12
FONT_SIZE_BODY = 13
FONT_SIZE_BUTTON = 14
FONT_SIZE_ICON = 15
FONT_SIZE_HEADER = 16
FONT_SIZE_TITLE = 18
FONT_SIZE_SECTION = 20
FONT_SIZE_MODAL_TITLE = 24
FONT_SIZE_HERO = 28
FONT_SIZE_MEGA = 32

# --- Shared component dimensions ---
CONTROL_HEIGHT_TINY = 26
CONTROL_HEIGHT_SMALL = 28
CONTROL_HEIGHT_MEDIUM = 30
CONTROL_HEIGHT_ENTRY = 38
CONTROL_HEIGHT_BUTTON = 40
CONTROL_HEIGHT_ACTION = 42
CONTROL_HEIGHT_ICON_LARGE = 60
CONTROL_HEIGHT_HERO = 64

CONTROL_WIDTH_NAV = 30
CONTROL_WIDTH_ORDER = 32
CONTROL_WIDTH_ICON_SMALL = 35
CONTROL_WIDTH_ICON = 40
CONTROL_WIDTH_SWITCH = 42
CONTROL_WIDTH_PAGE_ENTRY = 45
CONTROL_WIDTH_SYNC = 60
CONTROL_WIDTH_METRICS_DETAILS = 72
CONTROL_WIDTH_REFRESH = 78
CONTROL_WIDTH_PAGE_LABEL = 80
CONTROL_WIDTH_CONSTRAINT_ENTRY = 90
CONTROL_WIDTH_DIRECTION = 110
CONTROL_WIDTH_MONTH_LABEL = 120
CONTROL_WIDTH_SORT_SELECTOR = 270
CONTROL_WRAP_METRIC_CARD = 155
CONTROL_WRAP_CONSTRAINT_LABEL = 420
CONTROL_WRAP_SORT_HINT = 610

# --- Modal dimensions ---
CONSTRAINTS_MODAL_GEOMETRY = "760x620"
CONSTRAINTS_MODAL_MIN_WIDTH = 640
CONSTRAINTS_MODAL_MIN_HEIGHT = 540
SORT_SELECTOR_MODAL_GEOMETRY = "720x560"
SORT_SELECTOR_MODAL_MIN_WIDTH = 640
SORT_SELECTOR_MODAL_MIN_HEIGHT = 500
SORT_SELECTOR_ROW_HEIGHT = 56

# --- Timings ---
TOOLTIP_DELAY_MS = 400
TOOLTIP_AUTO_HIDE_MS = 3000

# --- Display text tokens ---
EMPTY_VALUE_TEXT = "—"
